#!/bin/sh
# autopkgtest check: Build and run the upstream test suite.
# (C) 2012 Canonical Ltd.
# Author: Daniel Kessel <d.kessel@gmx.de>

# running the mysql testsuite as described in:
# https://bugs.launchpad.net/ubuntu/+source/mysql-5.5/+bug/959683

echo "Running test 'testsuite'"
set -e

MTR_SKIP_TEST_LIST=$(mktemp)
ARCH=$(dpkg --print-architecture)

WORKDIR=$(mktemp -d)
trap 'rm -rf $WORKDIR $MTR_SKIP_TEST_LIST' 0 INT QUIT ABRT PIPE TERM
cd "$WORKDIR"

mkdir var
mkdir tmp

echo "using vardir: $WORKDIR/var"
echo "using tmpdir: $WORKDIR/tmp"

echo "Setting up skip-tests-list"

# Use the arch specific skiplists if exist, otherwise list is empty
if [ -f "/usr/share/mariadb/mariadb-test/unstable-tests.$ARCH" ]
then
  cat "/usr/share/mariadb/mariadb-test/unstable-tests.$ARCH" >> "$MTR_SKIP_TEST_LIST"
fi

# Store skipped test list in artifacts so it can be viewed while debugging
# failed autopkgtest runs
cp -v "$MTR_SKIP_TEST_LIST" "$AUTOPKGTEST_ARTIFACTS"

cd /usr/share/mariadb/mariadb-test
echo "starting mysql-test-tun.pl..."
export MTR_PRINT_CORE=detailed
# The $MTR_ARGUMENTS_APPEND is intentionally used to pass in extra arguments
# shellcheck disable=SC2086
eatmydata perl -I. ./mysql-test-run.pl \
    --force --testcase-timeout=120 --suite-timeout=540 --retry=3 \
    --verbose-restart --max-save-core=1 --max-save-datadir=1 \
    --parallel=auto --skip-rpl --suite=main \
    --skip-test-list="$MTR_SKIP_TEST_LIST" \
    --vardir="$WORKDIR/var" --tmpdir="$WORKDIR/tmp" \
    --xml-report="$AUTOPKGTEST_ARTIFACTS/mysql-test-run-junit.xml" \
    $MTR_ARGUMENTS_APPEND \
    "$@" 2>&1
echo "run: OK"
