[DEFAULT]
# Ignore requirement to use branch name 'master' to make it easier
# for contributors to work with feature and bugfix branches
ignore-branch = True

# Always sign everything
sign-tags = True
upstream-signatures = on

# DEP-14 format
debian-branch = ubuntu-22.04
debian-tag = ubuntu/%(version)s
debian-tag-msg = %(pkg)s Ubuntu release %(version)s
upstream-branch = 10.6
upstream-tag = mariadb-%(version)s

# MariaDB has submodules
submodules = True
