[DEFAULT]
# Ignore requirement to use branch name 'master' to make it easier
# for contributors to work with feature and bugfix branches
ignore-branch = True

# Always use pristine tar
pristine-tar = True

# Always sign everything
sign-tags = True
upstream-signatures = on

# DEP-14 format
debian-branch = ubuntu/24.04-noble
upstream-branch = upstream/latest

# Upstream tag format
upstream-vcs-tag = mariadb-%(version)s

# MariaDB has submodules
submodules = True

# Ubuntu tags and messages
debian-tag = ubuntu/%(version)s
debian-tag-msg = %(pkg)s Ubuntu release %(version)s
