[DEFAULT]
# DEP-14 format
debian-branch = ubuntu/24.10-oracular

# These options are used for upstream tarball imports, with each import done on
# branch 'upstream/latest' and tagged 'upstream/%(version)s'. Older upstream
# relases should be imported to branches like `upstream/10.11` or
# `upstream/10.6`.
upstream-branch = upstream/latest
upstream-tag = upstream/%(version)s

# This git repository hosts also the actual upstream main branch '11.4' and
# tags. Configure the upstream tag format below, so that `gbp import-orig` will
# run correctly, and link them to the equivalent tarball import branch and
# tarball import branch tag.
upstream-vcs-tag = mariadb-%(version)s

# Check that upstream git tags signed
upstream-signatures = on

# Always use pristine tar
pristine-tar = True

# Lax requirement to use branch name 'debian/latest' so that git-buildpackage
# will always build using the currently checked out branch as the Debian branch.
# This makes it easier for contributors to work with feature and bugfix
# branches.
ignore-branch = True

# Ensure the Debian Developer tagging releases automatically signs them
sign-tags = True

# MariaDB has submodules
submodules = True

# Ubuntu maintenance
debian-tag = ubuntu/%(version)s
debian-tag-msg = %(pkg)s Ubuntu release %(version)s
dch-opt = --vendor=ubuntu
